// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgLAcI3T2CYOdD-7Alqetgy3DRKWFOuMY',
    appId: '1:145525055434:web:aa0f268464b0083ba37933',
    messagingSenderId: '145525055434',
    projectId: 'top-events-a004e',
    authDomain: 'top-events-a004e.firebaseapp.com',
    storageBucket: 'top-events-a004e.appspot.com',
    measurementId: 'G-Q7LEVL6RDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3F1nIBjYWrDIHb4BvG87eZBwBKwYskok',
    appId: '1:145525055434:android:3fbac9c4369fd171a37933',
    messagingSenderId: '145525055434',
    projectId: 'top-events-a004e',
    storageBucket: 'top-events-a004e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMRQWaUUlusneg1xqNuAFTEaaHR0OyO24',
    appId: '1:145525055434:ios:1544004e4e188999a37933',
    messagingSenderId: '145525055434',
    projectId: 'top-events-a004e',
    storageBucket: 'top-events-a004e.appspot.com',
    iosBundleId: 'com.example.topEvents',
  );
}
